# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('address_3', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_open', models.IntegerField()),
                ('monday_close', models.IntegerField()),
                ('tuesday_open', models.IntegerField()),
                ('tuesday_close', models.IntegerField()),
                ('wednesday_open', models.IntegerField()),
                ('wednesday_close', models.IntegerField()),
                ('thursday_open', models.IntegerField()),
                ('thursday_close', models.IntegerField()),
                ('friday_open', models.IntegerField()),
                ('friday_close', models.IntegerField()),
                ('saturday_open', models.IntegerField()),
                ('saturday_close', models.IntegerField()),
                ('sunday_open', models.IntegerField()),
                ('sunday_close', models.IntegerField()),
            ],
        ),
    ]
