# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('overall_rating', models.FloatField()),
                ('phone_number', models.BigIntegerField()),
                ('website', models.CharField(max_length=100)),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Coordinates')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Location')),
                ('opening_times', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.OpeningTimes')),
            ],
        ),
    ]
