# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_coordinates_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='latitude',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='coordinates',
            name='longitude',
            field=models.FloatField(default=None),
        ),
    ]
